using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NaturalCommands.Models;

namespace NaturalCommands.Helpers
{
    public static class QuickClickTalonGenerator
    {
        private const string Header = "# Auto-generated by NaturalCommands Quick Clicks — do not edit manually" + "\n\n";

        public static void GenerateFromProfiles(IEnumerable<QuickClickProfile> profiles)
        {
            try
            {
                var list = profiles?.ToList() ?? new List<QuickClickProfile>();
                if (list.Count == 0)
                {
                    // remove any existing output files? no — just return
                    return;
                }

                // group regions by process name
                var byProcess = list
                    .GroupBy(p => p.ProcessName, StringComparer.OrdinalIgnoreCase)
                    .ToDictionary(g => g.Key, g => g.SelectMany(p => p.Regions).ToList(), StringComparer.OrdinalIgnoreCase);

                var outputDir = GetOutputDirectory();
                Directory.CreateDirectory(outputDir);

                foreach (var kv in byProcess)
                {
                    var processName = SanitizeFileName(kv.Key);
                    var regions = kv.Value;
                    var lines = new StringBuilder();
                    lines.Append(Header);

                    // dedupe by effective voice command
                    var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    foreach (var r in regions)
                    {
                        var voice = r.EffectiveVoiceCommand.Trim();
                        if (string.IsNullOrWhiteSpace(voice)) continue;
                        if (seen.Contains(voice)) continue;
                        seen.Add(voice);

                        // bare name -> invokes bare-name in NaturalCommands (which defaults to left click)
                        lines.AppendLine($"^{EscapeTalon(voice)}$:");
                        lines.AppendLine($"    user.run_application_csharp_natural(\"{EscapeForTalonInvocation(voice)}\")");

                        // explicit variants
                        lines.AppendLine($"^click {EscapeTalon(voice)}$:");
                        lines.AppendLine($"    user.run_application_csharp_natural(\"click {EscapeForTalonInvocation(voice)}\")");

                        lines.AppendLine($"^double click {EscapeTalon(voice)}$:");
                        lines.AppendLine($"    user.run_application_csharp_natural(\"double click {EscapeForTalonInvocation(voice)}\")");

                        lines.AppendLine($"^right click {EscapeTalon(voice)}$:");
                        lines.AppendLine($"    user.run_application_csharp_natural(\"right click {EscapeForTalonInvocation(voice)}\")");

                        lines.AppendLine();
                    }

                    var filename = Path.Combine(outputDir, $"quick_clicks_{processName}.talon");
                    File.WriteAllText(filename, lines.ToString(), Encoding.UTF8);
                    try { Logger.LogDebug($"QuickClickTalonGenerator: wrote {filename}"); } catch { }
                }
            }
            catch (Exception ex)
            {
                try { Logger.LogError($"QuickClickTalonGenerator failed: {ex.Message}"); } catch { }
            }
        }

        private static string GetOutputDirectory()
        {
            var configured = AppSettings.Instance?.QuickClicks?.TalonOutputDirectory;
            if (!string.IsNullOrWhiteSpace(configured))
            {
                try
                {
                    return Path.GetFullPath(Environment.ExpandEnvironmentVariables(configured));
                }
                catch { /* fallback below */ }
            }

            return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "talon_output");
        }

        private static string SanitizeFileName(string s)
        {
            var invalid = Path.GetInvalidFileNameChars();
            var cleaned = new string(s.Where(ch => !invalid.Contains(ch)).ToArray());
            return string.IsNullOrWhiteSpace(cleaned) ? "unknown" : cleaned.ToLowerInvariant();
        }

        private static string EscapeTalon(string s)
        {
            // minimal escaping for talon regex (keep it simple)
            return s.Replace("/", "\\/").Replace("\"", "\\\"");
        }

        private static string EscapeForTalonInvocation(string s)
        {
            // used inside the generated C# string in the talon file
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
